const soliditySyntax = [
    // Compiler Directives
    { category: "Compiler Directives" },
    {
        id: 1,
        name: "Pragma Directive",
        syntax: "pragma solidity ^0.8.0;",
        description: "Specifies the compiler version",
        param: "",
        param_count: 0,
    },
    {
        id: 2,
        name: "Importing Other Contracts",
        syntax: "import \"./$OtherContract$.sol\";",
        description: "Dependency management",
        param: "",
        param_count: 1,
    },

    // Contract Structure
    { category: "Contract Structure" },
    {
        id: 3,
        name: "Contract Declaration",
        syntax: "contract $MyContract$ {}",
        description: "Defines a new smart contract",
        param: "",
        param_count: 1,
    },
    {
        id: 4,
        name: "Interfaces",
        syntax: "interface $IERC20$ { function $transfer$($address$ $to$, $uint256$ $amount$) external returns ($bool$); }",
        description: "Abstract contract definitions",
        param: "",
        param_count: 5,
    },
    {
        id: 5,
        name: "Inheritance",
        syntax: "contract $Child$ is $Parent$ {}",
        description: "Contract inheritance",
        param: "",
        param_count: 2,
    },
    {
        id: 6,
        name: "Using Libraries",
        syntax: "using $SafeMath$ for $uint256$;",
        description: "Library attachment to types",
        param: "",
        param_count: 2,
    },

    // Data Types & Variables
    { category: "Data Types & Variables" },
    {
        id: 7,
        name: "State Variables",
        syntax: "$uint256$ public $myNumber$;",
        description: "Variables stored on the blockchain",
        param: "",
        param_count: 2,
    },
    {
        id: 8,
        name: "Structs",
        syntax: "struct $Person$ { $string$ $name$; $uint$ $age$; }",
        description: "Custom data structures",
        param: "",
        param_count: 3,
    },
    {
        id: 9,
        name: "Enums",
        syntax: "enum $State$ { $Created$, $Active$, $Inactive$ }",
        description: "Custom type with discrete values",
        param: "",
        param_count: 4,
    },
    {
        id: 10,
        name: "Arrays",
        syntax: "$uint256$[] public $dynamicArray$; $uint256$[5] public $fixedArray$;",
        description: "Collection types",
        param: "",
        param_count: 2,
    },
    {
        id: 11,
        name: "Mappings",
        syntax: "mapping($address$ => $uint256$) public $balances$;",
        description: "Key-value storage",
        param: "",
        param_count: 3,
    },
    {
        id: 12,
        name: "Type Conversions",
        syntax: "$uint8$ $y$ = $uint8$($x$);",
        description: "Explicit type conversion",
        param: "",
        param_count: 3,
    },

    // Functions
    { category: "Functions" },
    {
        id: 13,
        name: "Functions",
        syntax: "function $myFunction$($uint256$ $x$) public view returns ($uint256$) {}",
        description: "Executable code blocks",
        param: "",
        param_count: 3,
    },
    {
        id: 14,
        name: "Function Modifiers",
        syntax: "modifier $onlyOwner$() { require($msg.sender$ == $owner$, \"Not owner\"); _; }",
        description: "Reusable function guards",
        param: "",
        param_count: 2,
    },
    {
        id: 15,
        name: "Function Visibility",
        syntax: "function $publicFunc$() public {}",
        description: "Controls access to functions",
        param: "",
        param_count: 1,
    },
    {
        id: 16,
        name: "Function State Mutability",
        syntax: "function $viewFunc$() view returns ($uint$) {}",
        description: "Specifies function's interaction with state",
        param: "",
        param_count: 2,
    },
    {
        id: 17,
        name: "Constructor",
        syntax: "constructor() { $owner$ = $msg.sender$; }",
        description: "Initialization function",
        param: "",
        param_count: 2,
    },
    {
        id: 18,
        name: "Fallback Function",
        syntax: "fallback() external payable {}",
        description: "Default function when no other matches",
        param: "",
        param_count: 0,
    },
    {
        id: 19,
        name: "Receive Ether Function",
        syntax: "receive() external payable {}",
        description: "Handles plain Ether transfers",
        param: "",
        param_count: 0,
    },
    {
        id: 20,
        name: "Function Calls",
        syntax: "this.$myFunction$(); $otherContract$.$function$();",
        description: "Internal and external calls",
        param: "",
        param_count: 3,
    },

    // Events & Logging
    { category: "Events & Logging" },
    {
        id: 21,
        name: "Events",
        syntax: "event $ValueChanged$($address$ indexed $changer$, $uint256$ $newValue$);",
        description: "Emitted for off-chain consumption",
        param: "",
        param_count: 3,
    },

    // Control Structures
    { category: "Control Structures" },
    {
        id: 22,
        name: "Conditionals",
        syntax: "if ($x$ > 10) {} else {}",
        description: "Control flow",
        param: "",
        param_count: 1,
    },
    {
        id: 23,
        name: "Loops",
        syntax: "for ($uint$ $i$ = 0; $i$ < 10; $i$++) {} while ($x$ > 0) { $x$--; }",
        description: "Iteration structures",
        param: "",
        param_count: 2,
    },
    {
        id: 24,
        name: "Error Handling",
        syntax: "require($condition$, \"Error message\"); assert($condition$); revert(\"Error message\");",
        description: "Exception handling",
        param: "",
        param_count: 3,
    },

    // Blockchain Interactions
    { category: "Blockchain Interactions" },
    {
        id: 25,
        name: "Address Operations",
        syntax: "$address$ payable $recipient$ = payable($0x123...$); $recipient$.transfer($amount$);",
        description: "Address type utilities",
        param: "",
        param_count: 3,
    },
    {
        id: 26,
        name: "Global Variables",
        syntax: "$msg.sender$; $msg.value$; $block.timestamp$;",
        description: "Blockchain context variables",
        param: "",
        param_count: 0,
    },
    {
        id: 27,
        name: "Delegated Calls",
        syntax: "($bool$ $success$, ) = $address$($otherContract$).delegatecall($abi.encodeWithSignature$(\"$function$()\"));",
        description: "Delegate execution context",
        param: "",
        param_count: 4,
    },
    {
        id: 28,
        name: "Selfdestruct",
        syntax: "selfdestruct(payable($recipient$));",
        description: "Contract termination",
        param: "",
        param_count: 1,
    },

    // Data Manipulation
    { category: "Data Manipulation" },
    {
        id: 29,
        name: "ABI Encoding/Decoding",
        syntax: "$abi.encode$(...); $abi.decode$($bytesData$, ($types$));",
        description: "Data serialization",
        param: "",
        param_count: 3,
    },

    // Low-Level Operations
    { category: "Low-Level Operations" },
    {
        id: 30,
        name: "Assembly (Inline)",
        syntax: "assembly { /* Yul code */ }",
        description: "Low-level EVM operations",
        param: "",
        param_count: 0,
    }
];

export default soliditySyntax;